[package]
name = "libsql"
version = "0.1.0"
authors = ["Romario Lopez <hi@rlopzc.com>"]
license = "MIT"
edition = "2021"

[lib]
name = "libsql"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
